# Generated by Django 6.0.5 on 2026-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Google Maps location link'),
        ),
    ]
